# Replace {folder-name} with the output name from the .zip file generated by Paligo.
import os, glob

try:
    os.rmdir('../1132-Help_Center-html5_-Help_Center/out')
    os.rmdir('../1132-Help_Center-html5_-Help_Center')
    os.remove('../1132-Help_Center-html5_-Help_Center_-Upload_to_GitHub.zip')
    print('Deleted unneeded sub-directories...')
    
except:
   print('[ERROR!] Unable to delete files.')

# Version 1 of unzip-util, see https://github.com/johnapaz/unzip-util for details.
